import { NextResponse } from "next/server";
import { getAuth,signInWithEmailAndPassword } from "firebase/auth";
import { app } from "@/app/_private/firebaseConfig";
export async function POST(request) {
    const {Email,Password}=await request.json();
    const auth=getAuth(app);
    try {
        const userCredential = await signInWithEmailAndPassword(auth, Email, Password);
        console.log("User signed in:", userCredential.user);
        return NextResponse.json({
            Result:"success",
            Success:"Got it"
        })
        // Handle successful sign-in (e.g., redirect to another page)
      } catch (error) {
        console.error("Error signing in:", error);
        // console.log(error.code)
        return NextResponse.json({
            Result:error.code,
            Success:"Error"
        })
      }
    
}
/*
User signed in: <ref *1> UserImpl {
  providerId: 'firebase',
  proactiveRefresh: ProactiveRefresh {
    user: [Circular *1],
    isRunning: false,
    timerId: null,
    errorBackoff: 30000
  },
  reloadUserInfo: {
    localId: 'ZjhOjASNupYNXgcsmYy5c90QGup1',
    email: 'test@gmail.com',
    passwordHash: 'UkVEQUNURUQ=',
    emailVerified: false,
    passwordUpdatedAt: 1722973712986,
    providerUserInfo: [ [Object] ],
    validSince: '1722973712',
    lastLoginAt: '1722973712986',
    createdAt: '1722973712986',
    lastRefreshAt: '2024-08-06T19:48:32.986Z'
  },
  reloadListener: null,
  uid: 'ZjhOjASNupYNXgcsmYy5c90QGup1',
  auth: <ref *2> AuthImpl {
    app: FirebaseAppImpl {
      _isDeleted: false,
      _options: [Object],
      _config: [Object],
      _name: '[DEFAULT]',
      _automaticDataCollectionEnabled: false,
      _container: [ComponentContainer]
    },
    heartbeatServiceProvider: Provider {
      name: 'heartbeat',
      container: [ComponentContainer],
      component: [Component],
      instances: [Map],
      instancesDeferred: Map(0) {},
      instancesOptions: [Map],
      onInitCallbacks: Map(0) {}
    },
    appCheckServiceProvider: Provider {
      name: 'app-check-internal',
      container: [ComponentContainer],
      component: null,
      instances: Map(0) {},
      instancesDeferred: Map(0) {},
      instancesOptions: Map(0) {},
      onInitCallbacks: Map(0) {}
    },
    config: {
      apiKey: 'AIzaSyCS9fiK5_38SxhmGvV3Nx4BoKE95hWC4gs',
      authDomain: 'eflare-34fdf.firebaseapp.com',
      clientPlatform: 'Node',
      apiHost: 'identitytoolkit.googleapis.com',
      tokenApiHost: 'securetoken.googleapis.com',
      apiScheme: 'https',
      sdkClientVersion: 'Node/JsCore/10.12.4/FirebaseCore-web'
    },
    currentUser: [Circular *1],
    emulatorConfig: null,
    operations: Promise {
      undefined,
      [Symbol(async_id_symbol)]: 2257441,
      [Symbol(trigger_async_id_symbol)]: 2256063,
      [Symbol(kResourceStore)]: [Object],
      [Symbol(kResourceStore)]: [Object],
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: [Object],
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined
    },
    authStateSubscription: Subscription {
      auth: [Circular *2],
      observer: [ObserverProxy],
      addObserver: [Function: bound subscribe]
    },
    idTokenSubscription: Subscription {
      auth: [Circular *2],
      observer: [ObserverProxy],
      addObserver: [Function: bound subscribe]
    },
    beforeStateQueue: AuthMiddlewareQueue { auth: [Circular *2], queue: [] },
    redirectUser: null,
    isProactiveRefreshEnabled: false,
    EXPECTED_PASSWORD_POLICY_SCHEMA_VERSION: 1,
    _canInitEmulator: false,
    _isInitialized: true,
    _deleted: false,
    _initializationPromise: Promise {
      undefined,
      [Symbol(async_id_symbol)]: 2256063,
      [Symbol(trigger_async_id_symbol)]: 2256056,
      [Symbol(kResourceStore)]: [Object],
      [Symbol(kResourceStore)]: [Object],
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: [Object],
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined,
      [Symbol(kResourceStore)]: undefined
    },
    _popupRedirectResolver: null,
    _errorFactory: ErrorFactory {
      service: 'auth',
      serviceName: 'Firebase',
      errors: [Object]
    },
    _agentRecaptchaConfig: null,
    _tenantRecaptchaConfigs: {},
    _projectPasswordPolicy: null,
    _tenantPasswordPolicies: {},
    lastNotifiedUid: 'ZjhOjASNupYNXgcsmYy5c90QGup1',
    languageCode: null,
    tenantId: null,
    settings: { appVerificationDisabledForTesting: false },
    frameworks: [],
    name: '[DEFAULT]',
    clientVersion: 'Node/JsCore/10.12.4/FirebaseCore-web',
    persistenceManager: PersistenceUserManager {
      persistence: [InMemoryPersistence],
      auth: [Circular *2],
      userKey: 'authUser',
      fullUserKey: 'firebase:authUser:AIzaSyCS9fiK5_38SxhmGvV3Nx4BoKE95hWC4gs:[DEFAULT]',
      fullPersistenceKey: 'firebase:persistence:AIzaSyCS9fiK5_38SxhmGvV3Nx4BoKE95hWC4gs:[DEFAULT]',
      boundEventHandler: [Function: bound _onStorageEvent] AsyncFunction
    }
  },
  stsTokenManager: StsTokenManager {
    refreshToken: 'AMf-vBwKDVEXBMlZpHhUlBTYbWWF1gl89O6S7_q9EyAmbMIWISZLHrGSmPkpAksxtkXKD0IWirXtDAKlLA438YjitW7MnLe_fLDXhNERXJIXm3hJUlsbyS1n2frwmbiYAufGSYM9xrQZb-HtvVeLQYNnnNZwBO84wk3HzsYxNLFK3-_7OjcVUCtFxcyIgHbW_V47yEtgZ1aQ',
    accessToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImNlMzcxNzMwZWY4NmViYTI5YTUyMTJkOWI5NmYzNjc1NTA0ZjYyYmMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWZsYXJlLTM0ZmRmIiwiYXVkIjoiZWZsYXJlLTM0ZmRmIiwiYXV0aF90aW1lIjoxNzIyOTczNzQ4LCJ1c2VyX2lkIjoiWmpoT2pBU051cFlOWGdjc21ZeTVjOTBRR3VwMSIsInN1YiI6IlpqaE9qQVNOdXBZTlhnY3NtWXk1YzkwUUd1cDEiLCJpYXQiOjE3MjI5NzM3NDgsImV4cCI6MTcyMjk3NzM0OCwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.scQq2dBrL0fv8WMB2bpyDXpOV2cQqilyXefvWLyGNCJE--bYv5vJdwfXO01MaeYRm5NDt91IByY4hliZQKk29hyVLV5cQPfnvJwZZjZHttsxyMCS-C7dVXFlCgrmpnNHX44--jMW4qM16FPnv9SByXlxTcn0jqJXYrrwhNDWFgt_Vy1DgMEskzke28xiGTfTmTSodDjdm2f94Vf8nGYCVDBQqlBa2UiEBxlptBO77NJx35zkCVgLx5egayburJN_csAE5niYs1eqcQt4eUEWEpRL-l1yKexWxAbBDpY4aYRfOoSPYQ4TaxnejJs1NACjFbiJyGCp8ldOrGrarj0Phw',
    expirationTime: 1722977349097
  },
  accessToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImNlMzcxNzMwZWY4NmViYTI5YTUyMTJkOWI5NmYzNjc1NTA0ZjYyYmMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWZsYXJlLTM0ZmRmIiwiYXVkIjoiZWZsYXJlLTM0ZmRmIiwiYXV0aF90aW1lIjoxNzIyOTczNzQ4LCJ1c2VyX2lkIjoiWmpoT2pBU051cFlOWGdjc21ZeTVjOTBRR3VwMSIsInN1YiI6IlpqaE9qQVNOdXBZTlhnY3NtWXk1YzkwUUd1cDEiLCJpYXQiOjE3MjI5NzM3NDgsImV4cCI6MTcyMjk3NzM0OCwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.scQq2dBrL0fv8WMB2bpyDXpOV2cQqilyXefvWLyGNCJE--bYv5vJdwfXO01MaeYRm5NDt91IByY4hliZQKk29hyVLV5cQPfnvJwZZjZHttsxyMCS-C7dVXFlCgrmpnNHX44--jMW4qM16FPnv9SByXlxTcn0jqJXYrrwhNDWFgt_Vy1DgMEskzke28xiGTfTmTSodDjdm2f94Vf8nGYCVDBQqlBa2UiEBxlptBO77NJx35zkCVgLx5egayburJN_csAE5niYs1eqcQt4eUEWEpRL-l1yKexWxAbBDpY4aYRfOoSPYQ4TaxnejJs1NACjFbiJyGCp8ldOrGrarj0Phw',
  displayName: null,
  email: 'test@gmail.com',
  emailVerified: false,
  phoneNumber: null,
  photoURL: null,
  isAnonymous: false,
  tenantId: null,
  providerData: [
    {
      providerId: 'password',
      uid: 'test@gmail.com',
      displayName: null,
      email: 'test@gmail.com',
      phoneNumber: null,
      photoURL: null
    }
  ],
  metadata: UserMetadata {
    createdAt: '1722973712986',
    lastLoginAt: '1722973712986',
    lastSignInTime: 'Tue, 06 Aug 2024 19:48:32 GMT',
    creationTime: 'Tue, 06 Aug 2024 19:48:32 GMT'
  }
}
*/